# Generated by Django 4.2.7 on 2023-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0002_alter_auto_color_alter_auto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(choices=[('BLA', 'Blanco'), ('NEG', 'Blanco'), ('ROJ', 'ROJO')], default='BLA', max_length=3),
        ),
        migrations.AlterField(
            model_name='auto',
            name='transmision',
            field=models.CharField(choices=[('A', 'AUTOMÁTICA'), ('M', 'MANUAL')], default='M', max_length=1),
        ),
    ]
